services:
  dcbot:
    build: .
    container_name: dcbot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      # 持久化收藏数据
      - ./collections:/app/collections
      # 持久化用户配置
      - ./user_config.json:/app/user_config.json
